### ISSUE TITLE
Query around web streams / node.js streams

### ISSUE THREAD

**Issue by hazzlim** [dan-online/bunnycdn-stream#109]
First things first, thanks so much for building this - super useful tool!

I have quick question - I got a little stuck initially uploading videos, as I was creating a [web stream ](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) from a `File` object (obtained through a POST request from a html form) using [`File.stream()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream). However, despite the bunnycdn-stream API accepting that and returning a response without any issues, the video on the BunnyStream web interface was showing a 'processing failed' error.

I was able to fix things by converting the web stream into a node.js stream using [`stream.Readable.fromWeb(readable)`](https://nodejs.org/api/stream.html#streamwritablefromwebwritablestream-options).

Do you know if this is an issue on the BunnyStream end of things, or that AXIOS is not tolerating a web stream for some reason? 

Thanks! 

Hari

**Comment by dan-online** [comment]
Hey Hari,

I'm glad that this module can help! The BunnyCDN seems to have a fail-later type of api, in that it returns 200 before starting any processing that could fail. Judging by the form of data you seem to be dealing with, I would assume this has something to do with content type. The api believes and processes based on the content type header posted with the video data. I have this set to a stream mine-type however the File is probably a different format. A possible fix would be to add a content type optional parameter to the upload function so you can pass a more suitable mime, perhaps try forking and then finding which mime type is required. If that works feel free to open a pull request or feature request!

Thanks,
Dan

**Comment by dan-online** [comment]
Also quick side-note, you may want to look at direct uploads, where the user can upload direct to the BunnyCDN api 👀
