### ISSUE TITLE
feat: Support for public m3u8 url in fetch video api

### ISSUE THREAD

**Issue by mubin986** [dan-online/bunnycdn-stream#176]
### Description

Think about this scenario:-
I have a public m3u8 video url and i want to upload it to bunny stream. The thing I've to do now:-
- Manually download all the ts files and pack it into mp4 format
- Use upload video api to upload mp4 video to bunny stream

If it is possible to upload m3u8 directly to bunny stream with fetch video api, then it will be super cool!

**Comment by dan-online** [comment]
Hey @mubin986! I agree that for your purposes the fetchVideo api would be great and should definitely support that functionality. However this project simply hits the "fetchVideo" api of BunnyCDN, therefore I would recommend you contact them instead.

https://bunny.net/contact/

Best,
Dan
