### ISSUE TITLE
bug: createDirectUpload need a `collectionId` instead `collection`

### ISSUE THREAD

**Issue by jzambranoavvy** [dan-online/bunnycdn-stream#180]
### Description of the bug

When you try to use the function [createDirectUpload](https://github.com/dan-online/bunnycdn-stream/blob/main/docs/classes/BunnyCdnStream-1.md#createdirectupload) the documentation says that `collection` is optional which is correct but the right key should be `collectionId` because in the bunny documentation it is the right key used for `createVideo` function which is the internal function used in the `createDirectUpload`.

### Solution
![image](https://github.com/dan-online/bunnycdn-stream/assets/113395215/313cbd87-5a92-4ce8-acdf-206bdeb1f94e)

### Steps To Reproduce

1. Call `createDirectUpload` with the following parameters: title, collection.
2. Your video will upload in the root instead of the correct collection

**Comment by dan-online** [comment]
Hey @jzambranoavvy, thanks for the issue, I'll publish a patch for this soon
