### ISSUE TITLE
bug: type definition export

### ISSUE THREAD

**Issue by MyWay** [dan-online/bunnycdn-stream#218]
### Description of the bug

Could not find a declaration file for module 'bunnycdn-stream'. 'node_modules/bunnycdn-stream/dist/index.mjs' implicitly has an 'any' type.
  There are types at 'node_modules/bunnycdn-stream/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'bunnycdn-stream' library may need to update its package.json or typings.

### Steps To Reproduce

Install and import the library into a nuxt3 project.

**Comment by dan-online** [comment]
Hmm, that's odd, as far as I know, the code in [package.json#L7-L15](https://github.com/dan-online/bunnycdn-stream/blob/main/package.json#L7-L15) should be correctly declaring the types. 

After a quick test in a nuxt3 environment, I do see the same issue, and after a couple minutes and a few searches, it seems like #219 will fix this up

**Comment by dan-online** [comment]
Released in [v2.2.3](https://github.com/dan-online/bunnycdn-stream/releases/tag/v2.2.3)
