### ISSUE TITLE
bug: How to upload Express.Multer.File

### ISSUE THREAD

**Issue by piszczu4** [dan-online/bunnycdn-stream#235]
### Description of the bug

I'm using nestjs and I wanted to use `createAndUploadVideo` to upload the file. Unfortunately, file must be of `ReadStream` type and `createReadStream` does not work with `buffer` and `stream` properties of my multer file. Any ideas how can I make it work?

P.S. Why there is no `getVideoPlayData()` method implemented?

### Steps To Reproduce

...

**Comment by dan-online** [comment]
Hey @piszczu4, I believe you can do something like this:
```ts
const { Readable } = require('node:stream');

const stream = Readable.from(buffer);
```
To obtain a stream from a buffer

As for getVideoPlayData, if you could link the api in a feature request issue I'll check it out!
