### ISSUE TITLE
feat: add getVideoPlayData() method 

### ISSUE THREAD

**Issue by piszczu4** [dan-online/bunnycdn-stream#236]
### Description

There is an API method that is not implemented in the library: https://docs.bunny.net/reference/video_getvideoplaydata

Can we please add it? I'm asking because after uploading video with `createAndUploadVideo()` method, I want to access its `url`s and `length` to save to my database.

**Comment by dan-online** [comment]
Released in [v2.3.0](https://github.com/dan-online/bunnycdn-stream/releases/tag/v2.3.0) 🎉
