### ISSUE TITLE
NPM library does not work when using modules (instead of CommonJS)

### ISSUE THREAD

**Issue by Abdulazeez-98** [dan-online/bunnycdn-stream#70]
Hi,
I faced an issue while using Vitest to run some tests that include this library. My code normally compiles to CommonJS and it works fine, only when I use modules the problem occurs.
However, to reproduce this problem you don't actually need to be using TS, you can simply initialize a new npm project and install bunnycdn-stream library. Then set the type parameter in package.json to "module".

    npm init -y
    npm install bunnycdn-stream
package.json:

    // package.json:
    "type": "module"
Then create a very simple index.js:

    import { BunnyCdnStream } from 'bunnycdn-stream';
    const testBunny = new BunnyCdnStream({ apiKey: 'apiKey', videoLibrary: 'vidLib' });

When you run the file, the following error occurs:

![Xnip2023-01-30_23-38-09](https://user-images.githubusercontent.com/98826295/215589766-be266f6b-8945-43cd-aa7f-135480ff7f86.jpg)

I tried to investigate this problem. I think the problem is due to the version of Axios specified in the NPM library (which is 0.27.2). 
If you create a new empty NPM project and install axios@0.27.2 and do:

    import { AxiosError } from 'axios'

the same exact error will appear. I then tried using axios@1.2.6 and it did not show any error.

The package.json file in this GitHub repo specifies version 1.2.6 while the one on NPM specifies 0.27.2

I hope my input was helpful. I'm happy to provide more info if needed.

**Comment by dan-online** [comment]
Hey @Abdulazeez-98 feel free to try out version ``1.2.0``, where in theory this should be fixed!

**Comment by Abdulazeez-98** [comment]
The issue is indeed solved. Thank you very much! @dan-online
