### ISSUE TITLE
Library does not support CommonJS

### ISSUE THREAD

**Issue by Abdulazeez-98** [dan-online/bunnycdn-stream#81]
Hi,

I was trying to compile my TS code into CommonJS and I encountered this error at _runtime:_

![Xnip2023-02-05_17-49-36](https://user-images.githubusercontent.com/98826295/216826503-51583a3b-96db-4af0-be65-71602a36b3d3.jpg)

The same error can be reproduced when creating an empty JS project with the library 'file-type'.
It turned out that the library 'file-type' only supports ESM since version 17. However, version 16 (which supports CommonJS) appears to be still maintained. 

![Xnip2023-02-05_17-41-07](https://user-images.githubusercontent.com/98826295/216826029-273fe0ea-4143-4f04-9188-49a8c8488515.jpg)

I made a pull request to address this issue. The change only involves one function related to setting the thumbnail.
I hope my input was useful and happy to provide more info if needed 👍

**Comment by dan-online** [comment]
Resolved in #82
